### ISSUE TITLE
Best method

### ISSUE THREAD

**Issue by flype44** [Agg242/detect_vampire#1]
Nice.

But while the method used here works, it is unfortunately not future-proof.

For example, that module, VampireFastMem, may disappear one  day.

Also, it wont work on the ApolloOS distribution (AROS-based).

**For coders,**

Best method is to use the [Exec->AttnFlags](http://amigadev.elowar.com/read/ADCD_2.1/Includes_and_Autodocs_2._guide/node007C.html) by testing the BIT 10.
This bit stands for AC68080 (indirectly, if this CPU is present, then it means we run on a VAMPIRE board).

Example :
```
    include  exec/execbase.i
    include  exec/exec_lib.i

MAIN:
    move.l   $4.w,a6            ; ExecBase
    move.w   AttnFlags(a6),d0   ; ExecBase->AttnFlags
    btst     #10,d0             ; AC68080 Bit
    beq.s    .ok
    move.l   #0,d0
    rts
.ok
    move.l   #1,d0
    rts
```

**For end-users,**

Best method is to use the tool `VControl` shipped in the [SAGA Driver Pack](https://www.apollo-accelerators.com/wiki/doku.php/saga:updates).
It already provide some features for this exact purpose.
`VControl` use some Hardware method, which will not depend on the kickstart running modules.

https://github.com/flype44/VControl
https://github.com/flype44/VControl/blob/master/DOCUMENTATION.md#vcontrol-detect
https://github.com/flype44/VControl/blob/master/V_CPU_080.asm

**Comment by Agg242** [comment]
Thank you Flype.
As I am not able to cancel it from Aminet, I correct it. v1.1 now uses AttnFlags.
